### ISSUE TITLE
Issues with @ symbol processing

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/dtext_rb#22]
The @ symbol breaks the state machine when DText markers appear at the end of text, as it's looking for a word break for the mention so it skips over any closing markers such as style markers.

This issue is demonstrated at http://testbooru.donmai.us/comments/16

Not sure what should or shouldn't be allowed when @ appears at the beginning of a word, but if @ appears in any other location then it should probably not enter the mention state.

**Comment by evazion** [comment]
#23 still goes into the mention state, but leaves it immediately after the `@` so that parsing is resumed properly.

As I understand it, the reason we go into the mention state is because in order to determine that the mention occurs at the beginning of a word we need to look at the preceding characters, that is, we need lookbehind. AFAIK Ragel doesn't have a way to express lookbehind in patterns, hence we do it after entering the state.
